name: my_fyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Your packages
  speech_to_text: ^7.3.0
  http: ^1.2.0
  connectivity_plus: ^6.0.3
  flutter_launcher_icons: ^0.11.0
  avatar_glow: ^3.0.1
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon1.png
