import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';

class PdfService {
  static Future<void> generateAndOpenLecturePdf({
    required String title,
    String? courseCode,
    String? instructor,
    required String transcript,
    required String date,
  }) async {
    final pdf = pw.Document();

    // Load custom fonts with a fallback to avoid hanging without internet
    pw.Font font;
    pw.Font fontBold;
    try {
      font = await PdfGoogleFonts.poppinsRegular().timeout(
        const Duration(seconds: 3),
      );
      fontBold = await PdfGoogleFonts.poppinsBold().timeout(
        const Duration(seconds: 3),
      );
    } catch (e) {
      debugPrint("Font loading failed, falling back to standard fonts: $e");
      font = pw.Font.helvetica();
      fontBold = pw.Font.helveticaBold();
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title.toUpperCase(),
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 24,
                        color: PdfColors.blue800,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      date,
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 12,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                pw.PdfLogo(),
              ],
            ),
            pw.Divider(thickness: 2, color: PdfColors.blue800, height: 32),

            // Metadata Row
            pw.Row(
              children: [
                if (courseCode != null && courseCode.isNotEmpty) ...[
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "COURSE",
                        style: pw.TextStyle(
                          font: fontBold,
                          fontSize: 10,
                          color: PdfColors.grey600,
                        ),
                      ),
                      pw.Text(
                        courseCode,
                        style: pw.TextStyle(font: font, fontSize: 13),
                      ),
                    ],
                  ),
                  pw.SizedBox(width: 40),
                ],
                if (instructor != null && instructor.isNotEmpty) ...[
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        "INSTRUCTOR",
                        style: pw.TextStyle(
                          font: fontBold,
                          fontSize: 10,
                          color: PdfColors.grey600,
                        ),
                      ),
                      pw.Text(
                        instructor,
                        style: pw.TextStyle(font: font, fontSize: 13),
                      ),
                    ],
                  ),
                ],
              ],
            ),
            pw.SizedBox(height: 32),

            // Content Section
            pw.Text(
              "LECTURE TRANSCRIPT",
              style: pw.TextStyle(
                font: fontBold,
                fontSize: 14,
                color: PdfColors.blue700,
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Paragraph(
                text: transcript,
                style: pw.TextStyle(
                  font: font,
                  fontSize: 12,
                  lineSpacing: 2,
                  color: PdfColors.black,
                ),
                textAlign: pw.TextAlign.justify,
              ),
            ),

            // Footer
            pw.SizedBox(height: 40),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 8),
            pw.Center(
              child: pw.Text(
                "Generated by VoiceNoteX AI Assistant",
                style: pw.TextStyle(
                  font: font,
                  fontSize: 10,
                  color: PdfColors.grey400,
                ),
              ),
            ),
          ];
        },
      ),
    );

    // Save PDF
    final output = await getTemporaryDirectory();
    final sanitizedTitle = title.replaceAll(RegExp(r'[^a-zA-Z0-9_\-]'), '_');
    final fileName =
        "${sanitizedTitle}_${DateTime.now().millisecondsSinceEpoch}.pdf";
    final file = File("${output.path}/$fileName");
    await file.writeAsBytes(await pdf.save());

    // Open File
    final result = await OpenFilex.open(file.path);
    if (result.type != ResultType.done) {
      throw Exception("Could not open PDF: ${result.message}");
    }
  }
}
