import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';

class PdfService {
  static Future<void> generateAndOpenLecturePdf({
    required String title,
    String? courseCode,
    String? instructor,
    required String transcript,
    required String date,
  }) async {
    final pdf = pw.Document();

    // Load custom fonts if needed, or use standard
    final font = await PdfGoogleFonts.poppinsRegular();
    final fontBold = await PdfGoogleFonts.poppinsBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // Header
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      title.toUpperCase(),
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 24,
                        color: PdfColors.blue800,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      date,
                      style: pw.TextStyle(font: font, fontSize: 12, color: PdfColors.grey700),
                    ),
                  ],
                ),
                pw.PdfLogo(),
              ],
            ),
            pw.Divider(thickness: 2, color: PdfColors.blue800, height: 32),

            // Metadata Row
            pw.Row(
              children: [
                if (courseCode != null && courseCode.isNotEmpty) ...[
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text("COURSE", style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.grey600)),
                      pw.Text(courseCode, style: pw.TextStyle(font: font, fontSize: 13)),
                    ],
                  ),
                  pw.SizedBox(width: 40),
                ],
                if (instructor != null && instructor.isNotEmpty) ...[
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text("INSTRUCTOR", style: pw.TextStyle(font: fontBold, fontSize: 10, color: PdfColors.grey600)),
                      pw.Text(instructor, style: pw.TextStyle(font: font, fontSize: 13)),
                    ],
                  ),
                ],
              ],
            ),
            pw.SizedBox(height: 32),

            // Content Section
            pw.Text(
              "LECTURE TRANSCRIPT",
              style: pw.TextStyle(font: fontBold, fontSize: 14, color: PdfColors.blue700),
            ),
            pw.SizedBox(height: 12),
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Paragraph(
                text: transcript,
                style: pw.TextStyle(
                  font: font,
                  fontSize: 12,
                  lineSpacing: 2,
                  color: PdfColors.black,
                ),
                textAlign: pw.TextAlign.justify,
              ),
            ),

            // Footer
            pw.SizedBox(height: 40),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 8),
            pw.Center(
              child: pw.Text(
                "Generated by VoiceNoteX AI Assistant",
                style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey400),
              ),
            ),
          ];
        },
      ),
    );

    // Save PDF
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/${title.replaceAll(' ', '_')}.pdf");
    await file.writeAsBytes(await pdf.save());

    // Open File
    await OpenFilex.open(file.path);
  }
}
